#!/bin/zsh

# Interactive shell detection {{{

# If either of these are true, the shell is non-interactive.
# Exit without changing any settings or printing any output.
[[ $- != *i* ]] && return
[ -z "${PS1}" ] && return

# }}}

# Helper functions {{{

__stat_mode() {
    if [ "$(uname -s)" = "Darwin" ]; then
        stat -f '%A' "${@}"
    else
        stat -c '%a' "${@}"
    fi
}

__stat_mtime() {
    if [ "$(uname -s)" = "Darwin" ]; then
        stat -f '%m' "${@}"
    else
        stat -c '%Z' "${@}"
    fi
}

# }}}

# Basic settings {{{

# Increase session history size from the default 500
HISTSIZE=100000

# }}}

__prepend_path_if_exists() {
    # Remove any existing instances of directory from PATH
    PATH=$(echo "${PATH}" | sed -e 's/:/\n/g' | grep -ve "^${1}\$" | xargs | tr " " ":")
    # Prepend directory to PATH if directory exists
    [ -d "${1}" ] && PATH="${1}:${PATH}"
    return 0
}
__prepend_path_if_exists "/opt/homebrew/bin"
__prepend_path_if_exists "${HOME}/.dotfiles/bin"
__prepend_path_if_exists "${HOME}/.local/bin"
__prepend_path_if_exists "${HOME}/.ruby/bin"
__prepend_path_if_exists "${HOME}/bin"
__prepend_path_if_exists "${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnubin"
__prepend_path_if_exists "${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnuman"

# GnuPG configuration {{{

[ -t 0 ] && GPG_TTY=$(tty) && export GPG_TTY

# }}}

# ssh configuration {{{

if [ -z "${SSH_CONNECTION}" ]; then
    SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
    export SSH_AUTH_SOCK
fi

# }}}

# Docker configuration {{{

## Required to make podman and cosign work together
export DOCKER_CONFIG=~/.config/containers

# }}}

# Homebrew configuration {{{

export HOMEBREW_NO_ENV_HINTS=1

# }}}

# iterm configuration {{{
if [ "$(uname -s)" = "Darwin" ]; then
    if [ -n "${ITERM_PROFILE}" ]; then
        export ITERM_PROFILE
    fi
fi

if [ -n "${ITERM_PROFILE}" ]; then
    if [ -f "${HOME}/.iterm2_shell_integration.zsh" ]; then
        source "${HOME}/.iterm2_shell_integration.zsh"
    fi
fi

# }}}

# TabTab Configuration {{{
# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true
# }}}

# GO Configuration {{{
export GOPATH=$HOME/golang
export PATH=$PATH:$GOPATH/bin
# }}}

# NVM Configuration {{{
# If NVM configure
if [ ! -n "${GITHUB_CODESPACE_TOKEN}" ] && [ ! -n "${CODESPACES}" ]; then
    if ! command -v nvm &>/dev/null; then
        export NVM_DIR="$HOME/.nvm"
        [ -s "${HOMEBREW_PREFIX}/opt/nvm/nvm.sh" ] && . "${HOMEBREW_PREFIX}/opt/nvm/nvm.sh"                                       # This loads nvm
        [ -s "${HOMEBREW_PREFIX}/opt/nvm/etc/bash_completion.d/nvm" ] && . "${HOMEBREW_PREFIX}/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
    fi
fi

# Load additional configuration {{{

__source_if_exists() {
    if [ -f "${1}" ]; then
        . "${1}"
    fi
}

# Host-specific bashrc if available
__source_if_exists ~/.dotfiles/lib/bashrc."${HOSTNAME}"

# Aliases and helper functions
__source_if_exists ~/.dotfiles/shell/aliases

# Local configuration files
__source_if_exists ~/.local/shell-rc
__source_if_exists ~/.local/shell-aliases

# }}}

# Display basic settings on first invocation {{{

if [ ! -f "${DOTFILES_DATA}/first_run_complete" ]; then
    "${HOME}"/.dotfiles/bin/dotfiles-first-run
fi

# }}}

# Cleanup {{{

# Unset local helper functions
unset -f __source_if_exists
unset -f __prepend_path_if_exists
unset -f __stat_mode

# }}}
